---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 11-jdk

inputs:
- name: r2dbc-over-adba
- name: r2dbc-spi-artifactory

outputs:
- name: r2dbc-over-adba-artifactory

caches:
- path: maven

run:
  path: r2dbc-over-adba/ci/build.sh
